config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path, notice: 'Customer Created Successfully'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to customers_path, notice: 'Customer Successfully Updated'
    else
      render :edit
    end
  end

  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: 'Customer Deleted Successfully'
    end
  end
  
  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(
      :id,
      :name,
      :email,
      :phone,
      :avatar,
      :smoker
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.erb
<% if customer.errors.any? %>
  <ul>
    <% customer.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_for customer do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br/>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  <br/>
  <%= f.label :somker %> <br/>
  <% { 'Y': 'Yes', 'N': 'No'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %> <br/>
  <% end %>

  <%= f.submit 'Create Customer' %>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render partial: 'customers/form', locals: { customer: @customer} %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h1>Customers List</h1>
<%= link_to  'New Customer', new_customer_path %>

<br/>

<table id="custumers-table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.name %></td>
      <td><%= link_to 'Show', customer_path(customer.id) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer.id) %></td>
      <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render partial: 'customers/form', locals: { customer: @customer } %>

app/views/customers/show.html.erb
<h1>Showing User</h1>
<p>
    <strong>Name</strong>
    <%= @customer.name %>
</p>
<p>
    <strong>EMAIL</strong>
    <%= @customer.email %>
</p>
<p>
    <strong>Phone</strong>
    <%= @customer.phone %>
</p>
<p>
    <strong>Smoker</strong>
    <%= @customer.smoker %>
</p>

<p>
  <strong>Avatar</strong>
  <%= @customer.avatar %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<ul>
  <li><%= link_to  "Customers", customers_path %></li>
</ul>